### ISSUE TITLE
Target with Open Access licence pending is accessible via pywb

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-ui#212] opened 2018-11-20 16:59 UTC
I came across this target that has a licence pending, however it is accessible via python wayback without an “Available in Legal Deposit Library Reading Rooms only” message; I haven’t investigated it further but I reckon there could be other similar cases.

Target: https://www.webarchive.org.uk/act/targets/82735
![image](https://user-images.githubusercontent.com/18530934/48789484-13e15300-ece5-11e8-80b8-a1ef5f6ae3a7.png)

 

QA wayback:  https://www.webarchive.org.uk/act/wayback/20171201140536/https://sites.google.com/site/cavesofnorthwales/
![image](https://user-images.githubusercontent.com/18530934/48789493-19d73400-ece5-11e8-8f65-19c12b8d9630.png)

 

Pywb: https://www.webarchive.org.uk/wayback/en/archive/20171201140536/https://sites.google.com/site/cavesofnorthwales/
 
![image](https://user-images.githubusercontent.com/18530934/48789496-1cd22480-ece5-11e8-9688-0e97f1955807.png)

**Comment by ldbiz** [comment] 2018-11-22 11:07
I'm guessing this is a data/indexing issue as it affects multiple apps (UKWA shows no RRO warning) and they correctly give warnings on other sites. Will reassign @min2ha when we've determined that it needs a code investigation.

**Comment by ldbiz** [comment] 2018-11-22 11:41
@anjackson if you know what this issue is likely to be, please advise, or I'll investigate further.

**Comment by anjackson** [comment] 2018-11-22 12:09
This seems to be a problem with the access whitelist generated from W3ACT data. Ie not a problem with UKWA-UI.

**Comment by ldbiz** [comment] 2018-11-23 12:37
@min2ha Unrelated issue. 

The w3act code appears somewhere to be invalidly returning "Pending" targets as Valid for Open Access - which they are not. Still investigating, will assign it over to you when the issue is clear.

**Comment by nicolabingham** [comment] 2018-11-27 09:37
We did have a bug ages ago where sites on the same host (e.g https://sites.google.com/site/....... ) would all be whitelisted in if we have a permission for one domain on that host. Could that be happening here?

**Comment by anjackson** [comment] 2018-12-12 09:42
@nicolabingham Thanks, yes, the whole of Google Sites had somehow made it into the internal whitelist we use that dates from before the WCT-to-W3ACT migration.

I've removed it (https://github.com/ukwa/ukwa-manage/commit/291a7aa90397ce3207bb44d52456d9f47d45a069) and this should resolve tomorrow.

**Comment by anjackson** [comment] 2020-02-07 14:49
Appears to be fine now.

**Closed by anjackson** 2020-02-07 14:49 UTC
Labels: SOLR, bug, question
