### ISSUE TITLE
NLW has wrong hostname for their reading room Wayback service

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#175] opened 2018-10-09 09:16 UTC
Not sure where this has gone wrong, but I have lifted the correct one from Beta (which works for them).

https://github.com/ukwa/ukwa-ui/commit/755100fb44f569843f312306edcd6e31036c37ad

Unfortunately this will have to be tested by them when it rolls out.

**Comment by min2ha** [comment] 2018-10-11 12:52
It was committed to **master branch**
https://github.com/ukwa/ukwa-ui/commit/755100fb44f569843f312306edcd6e31036c37ad
but it is obvious that the Travis CI build failed:
https://travis-ci.org/ukwa/ukwa-ui/builds/439038589?utm_source=github_status&utm_medium=notification

Do we need to commit it to **development branch** before successful Travis CI build?

**Comment by ldbiz** [comment] 2018-10-11 13:13
Sorry, yes, I should have committed to dev I think so it needs pulling into that. I will leave that to you so I don't mess up anything else. 

CI Build is (or was) on Jenkins, I know nothing about the Travis setup.

**Comment by jasonwebber-bl** [comment] 2018-10-11 15:33
Is it right that we can't test this until it's on alpha?

**Comment by min2ha** [comment] 2018-10-11 15:42
IMHO we should be able to test it anywhere  and anytime, because configurations are identical.

**Comment by anjackson** [comment] 2018-10-11 15:52
Jenkins isn't involved in Alpha/Beta (only Dev). Currently we use the application properties in the Docker Container and only override the bits of configuration that vary between Alpha/Beta/Dev via environment variables.

I'd probably rather do that in future, but for now at least we could change the Docker deployments to use an updated configuration file.

**Comment by jasonwebber-bl** [comment] 2018-10-19 15:34
Aled has confirmed that it works fine now.

**Closed by jasonwebber-bl** 2018-10-19 15:34 UTC
Labels: Backend, bug, question, testing: ready to test
