### ISSUE TITLE
Links to reading rooms on 'Resource only available in a reading room' page all broken

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#38] opened 2017-12-01 14:26 UTC
Links to all the reading rooms are broken

**Comment by GilHoggarth** [comment] 2017-12-01 14:28
@jasonwebber-bl Could you add more information please. I.e., this is where this is seen, this is what is done to see this, the message that is communicated to the viewer....

**Comment by anjackson** [comment] 2017-12-01 14:37
Sorry, @jasonwebber-bl I logged this as #39!

**Comment by anjackson** [comment] 2017-12-01 14:38
Closing as a duplicate of #39.

**Closed by anjackson** 2017-12-01 14:38 UTC
